name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      - name: Run Cucumber all tests
        run: npm run test
      - name: Move Cucumber report to artifact folder
        run: mv reports/cucumber-report.html reports/index.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          # name: playwright-report
          # path: playwright-report/
          name: cucumber-report
          path: reports/
          retention-days: 30
      - name: Prepare artifacts for GitHub Pages
        run: |
          mkdir public
          cp reports/index.html public/
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
