name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      - name: Run Cucumber all tests
        run: npm run test
      - name: Move Cucumber report to artifact folder
        run: mv reports/cucumber-report.html reports/index.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          # name: playwright-report
          # path: playwright-report/
          name: cucumber-report
          path: reports/
          retention-days: 30
      - name: Prepare artifacts for GitHub Pages
        run: |
          mkdir public
          cp reports/index.html public/
      - name: Deploy to GitHub Pages
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          cp -r public/* .
          git add .
          git commit -m "Deploy GitHub Pages"
          git push -f origin gh-pages
